### ISSUE TITLE
Replace XP drops is toggled on but displays normal drops

### ISSUE THREAD

**Issue by colesie** [geeckon/instant-damage-calculator#1]
![image](https://user-images.githubusercontent.com/84428149/139513982-0a858c93-d72e-45bc-920b-3e4047f208e8.png)
As the title says, I have "replace xp drops" toggled yet attacking with any weapon still displays the normal xp drop. Display damage overlay does accurately show the latest damage, but I would rather toggle that off and have the xp drops replaced instead.

**Comment by geeckon** [comment]
Should be fixed by the latest fix. I'd like to mention that this plugin is going to look nicer when having "grouped" xp drops turned on.

**Comment by colesie** [comment]
> Should be fixed by the latest fix. I'd like to mention that this plugin is going to look nicer when having "grouped" xp drops turned on.

I can confirm that with grouped XP toggled on the XP drops are coming in nicely and they are surprisingly accurate. Thank you!

**Comment by aftrosrs** [comment]
i would like to reopen this as its not fixed
![Screenshot_86](https://user-images.githubusercontent.com/112984970/189664984-a1f7e212-6496-4a20-8ab1-520d4037fdbb.png)
![Screenshot_87](https://user-images.githubusercontent.com/112984970/189664988-447a5033-7ab1-4290-9fc5-4ca19eadb6a1.png)
